### ISSUE TITLE
Weather forecast extended data inconsistent based on location

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-data-weather#53] opened 2020-01-21 14:09 UTC
**What should happen**

Data provided in the `location.forecasts` array should be consistent for all locations. We would expect that the forecast data starts with the day following the current day e.g. current day is Tuesday so first forecast day is Wednesday.

**What currently happens**

If the location is outside of the US the data appears to work as expected, however if the location is in the US the first day in the forecast array is the same as the current day e.g. current day is Tuesday and first forecast day is also Tuesday.

**Steps to recreate**

Add a weather Template with extended weather to test locations and see the first day in the forecast list change.

**Comment by mmeiers** [comment] 2020-01-21 14:26
Note: This appears to happen at a certain time during the day. Around 3-5 EST.

**Comment by mmeiers** [comment] 2020-01-21 14:29
Looks like this may have come up again. https://trello.com/c/Fdt0NODO/6898-weather-component-validation-2

**Comment by ezequielc** [comment] 2020-01-21 14:30
@mmeiers @pcsandford If you have the data, please share with us as well. It will help with the investigation. Thanks!

**Comment by pcsandford** [comment] 2020-01-21 15:36
@ezequielc if you run the Weekly Weather Forecast Template in preview I have added in a console log for weather which will show as `Weather = Object` with the object having both current and forecast data. @mmeiers FYI Thanks!

**Comment by alex-deaconu** [comment] 2020-01-27 14:27
Main cause of the issue is the fact that we did not understand the behaviour of the API. We validated that there's no issue on our side with the parsing, and reached out to get more information on the behaviour.

Based on the information received, we updated the README as per the above.

Closing. Thanks!

**Closed by alex-deaconu** 2020-01-27 14:27 UTC
