### ISSUE TITLE
Weather shows incorrectly for a specific address in Australia

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-data-weather#71] opened 2020-05-22 16:17 UTC
### What is the expected behavior?
Weather should show the correct weather for your geographic location.

### What is the actual behavior?
Weather shows incorrectly for the address: 1 Echunga Rd, Terrey Hills NSW 2084, Australia

### What steps can be taken to replicate the problem?
Update your Display or Company to have the address listed above, and notice that the weather displayed does not match the weather of the location.

**Comment by olegrise** [comment] 2020-06-01 21:20
Basically the problem is that some addresses are ambiguous and the weather API returns the weather for the wrong address.

Here is the response from the customweather.com support:

> To search for location names and avoid ambiguity you should use the search product from the API. Here is an example.
> 
> http://xml.customweather.com/xml?client=&client_password=&version=2.0&product=search&search=Terrey Hills, Australia
> 
> From the output you would request the weather data using the ID from the "id" field, as so.
> 
> http://xml.customweather.com/xml?client=&client_password=&product=current_extended&metric=false&id=gn2147035

We can try using their search API. This API returns matching addresses, so we can find the address we need by comparing the country and postal code, and then when use location ID when requesting the weather forecast. 

Here is an example of what is returned by the search API:
```
<cw_citylist size="4" search_type="city">
<city id="W94320" name="Balgo Hills" state="WA" state_name="Western Australia" country="AS" country_name="Australia" lat="-20.1333" long="127.867" population="0" timezone="8" timezone_code="AWST" timezone_id="Australia/Perth" timezone_offset="28800" localtime="Tue, 02 Jun 2020 05:18:33 AWST" region="Australia" weather_id="W94315" iso_cc="AU"/>
<city id="W94315" name="Balgo Hills Asa" state="WA" state_name="Western Australia" country="AS" country_name="Australia" lat="-20.135" long="127.9892" population="0" timezone="8" timezone_code="AWST" timezone_id="Australia/Perth" timezone_offset="28800" localtime="Tue, 02 Jun 2020 05:18:33 AWST" region="Australia" weather_id="W94315" iso_cc="AU"/>
<city id="101001" name="Bonny Hills" state="NSW" state_name="New South Wales" country="AS" country_name="Australia" lat="-31.6" long="152.84" population="0" timezone="10" timezone_code="AEST" timezone_id="Australia/Sydney" timezone_offset="36000" localtime="Tue, 02 Jun 2020 07:18:33 AEST" region="Australia" weather_id="101001" iso_cc="AU"/>
<city id="W94622" name="Wongan Hills" state="WA" state_name="Western Australia" country="AS" country_name="Australia" lat="-30.8833" long="116.717" population="0" timezone="8" timezone_code="AWST" timezone_id="Australia/Perth" timezone_offset="28800" localtime="Tue, 02 Jun 2020 05:18:33 AWST" region="Australia" weather_id="W94619" iso_cc="AU"/>
</cw_citylist>
```

@ezequielc @alex-deaconu @alanclayton @stulees  FYI

**Comment by olegrise** [comment] 2020-06-09 18:51
Fixed in https://github.com/Rise-Vision/rise-data-weather/pull/72

**Closed by olegrise** 2020-06-09 18:51 UTC
