### ISSUE TITLE
Weather data returned for wrong country when city isn't an exact match

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-data-weather#78] opened 2020-11-27 18:02 UTC
### What is the expected behavior?
The customer sets their address in their company settings, which is used for weather data.  Weather data is returned accurately.

### What is the actual behavior?
In a case where an exact match for the city cannot be found, data is sometimes returned for another country or continent, causing the data to be wildly inaccurate.

### What steps can be taken to replicate the problem?
1. Create a presentation from the Weather Current Day Forecast template.
2. Set your address to Murroe, Co. Limerick, Limerick, Ireland, V94 HC84.  Data is returned accurately.
3. Compare with setting your address to Murroe, Co Limerick, Limerick, Ireland, V94 HC84.  Data is returned for Co, the Gambia, West Africa, where it is much hotter.
--

**Comment by olegrise** [comment] 2020-11-27 19:46
@PatrickA-RiseVision I can't reproduce it. I'm getting the same results for both addresses and both results are in Ireland. But even if we wanted to improve this, I'm not sure what can be done here. The weather component already compares City, State, and Country fields to find the best match. Not sure how we can improve that.

**Comment by PatrickA-RiseVision** [comment] 2020-11-27 20:03
@olegrise Weird, I was able to replicate it by switching it back to "Co Limerick" as the city (without the period).

re: how to improve it, not sure what to suggest.  It seems like it is weighing the city name much more heavily than the geographical location, currently, which I believe is the issue.  Có, the Gambia is nowhere near Co. Limerick, Ireland.

I'll defer to you on whether this is worth pursuing, but it is a defect.

**Comment by olegrise** [comment] 2020-11-27 20:23
@PatrickA-RiseVision sounds good. Since I was not able to replicate it, I can't even tell what weather API returns. It's quite possible that the "problem" is that their API matching algorithm does not even include this address as an option. Anyway, I'm going close it for now as there is nothing we can do about at this time.

**Closed by olegrise** 2020-11-27 20:23 UTC
